# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dream_Catcher' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dream_Catcher

  target 'Dream_Catcher-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'Dream_CatcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Dream_Catcher-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dream_Catcher-tvOS

  target 'Dream_Catcher-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
